apiVersion: v2
name: nextcloud
description: A Helm chart to deploy nextcloud with public DNS + TLS
type: application
version: 0.1.0
appVersion: "27.1.2"

dependencies:
  - name: nextcloud
    version: "4.3.5"
    repository: "https://nextcloud.github.io/helm/"
  - name: ingress-nginx
    version: "4.2.5"
    repository: "https://kubernetes.github.io/ingress-nginx"
  - name: external-dns
    version: "0.1.0"
