# Only deploy the respective ingress object if it does not already exist. Otherwise nginx complains about the host/path already being defined during upgrade.
{{- if .Values.app.enabled }}
{{- $exists := lookup "v1" "Ingress" .Release.Namespace "nextcloud-ingress" -}}
{{ if $exists }}
{{ else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.nextcloud.nextcloud.host }}
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
spec:
  tls:
  - hosts:
    - {{ .Values.nextcloud.nextcloud.host }}
    secretName: tls-cert
  rules:
  - host: {{ .Values.nextcloud.nextcloud.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 8080
  ingressClassName: nginx
{{- end -}}
{{- end }}
